mtacs_element = createElement("mtacs_element")

addEvent("onTeamChosen", true)
addEvent("onSpawn", true)
addEvent("onRoundEnding", true)
addEvent("onRoundStart", true)
addEvent("onRoundTimeout", true)
addEvent("onWeaponBuy", true)
addEvent("onVehicleBuy", true)
addEvent("onBombPlanted", true)
addEvent("onBombDefused", true)
addEvent("onBombExploded", true)
addEvent("onBombDropped", true)
addEvent("onBombPickedUp", true)
